spring.application.name=healthapp

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/health_app
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

openai.api-url=https://api.openai.com/v1/chat/completions
openai.api-model=gpt-4o-mini
openai.api-key=${GPT_KEY}

gemini.api-model=gemini-2.5-flash
gemini.api-key=${GEMINI_KEY}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}